/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as CategoryIndexRouteImport } from './routes/$category/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminAddProductRouteImport } from './routes/admin/add-product'
import { Route as AdminAddCategoryRouteImport } from './routes/admin/add-category'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountPaymentsRouteImport } from './routes/account/payments'
import { Route as CheckoutPostCheckoutRouteRouteImport } from './routes/checkout/post-checkout/route'
import { Route as ProductsProductIndexRouteImport } from './routes/products/$product/index'
import { Route as CheckoutPostCheckoutIndexRouteImport } from './routes/checkout/post-checkout/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminFrontpageIndexRouteImport } from './routes/admin/frontpage/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountAddressBookIndexRouteImport } from './routes/account/address-book/index'
import { Route as CategoryProductIndexRouteImport } from './routes/$category/$product/index'
import { Route as AdminFrontpageNewFrontpageRouteImport } from './routes/admin/frontpage/new-frontpage'
import { Route as AccountAddressBookNewAddressRouteImport } from './routes/account/address-book/new-address'
import { Route as AdminProductsIdIndexRouteImport } from './routes/admin/products/$id/index'
import { Route as AdminFrontpageIdIndexRouteImport } from './routes/admin/frontpage/$id/index'
import { Route as AdminCategoriesIdIndexRouteImport } from './routes/admin/categories/$id/index'
import { Route as AccountOrdersIdIndexRouteImport } from './routes/account/orders/$id/index'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products/$id/edit'
import { Route as AdminCategoriesIdEditRouteImport } from './routes/admin/categories/$id/edit'
import { Route as AccountAddressBookIdEditRouteImport } from './routes/account/address-book/$id/edit'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddProductRoute = AdminAddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAddCategoryRoute = AdminAddCategoryRouteImport.update({
  id: '/add-category',
  path: '/add-category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CheckoutPostCheckoutRouteRoute =
  CheckoutPostCheckoutRouteRouteImport.update({
    id: '/checkout/post-checkout',
    path: '/checkout/post-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsProductIndexRoute = ProductsProductIndexRouteImport.update({
  id: '/products/$product/',
  path: '/products/$product/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPostCheckoutIndexRoute =
  CheckoutPostCheckoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CheckoutPostCheckoutRouteRoute,
  } as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFrontpageIndexRoute = AdminFrontpageIndexRouteImport.update({
  id: '/frontpage/',
  path: '/frontpage/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAddressBookIndexRoute = AccountAddressBookIndexRouteImport.update({
  id: '/address-book/',
  path: '/address-book/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CategoryProductIndexRoute = CategoryProductIndexRouteImport.update({
  id: '/$category/$product/',
  path: '/$category/$product/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFrontpageNewFrontpageRoute =
  AdminFrontpageNewFrontpageRouteImport.update({
    id: '/frontpage/new-frontpage',
    path: '/frontpage/new-frontpage',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AccountAddressBookNewAddressRoute =
  AccountAddressBookNewAddressRouteImport.update({
    id: '/address-book/new-address',
    path: '/address-book/new-address',
    getParentRoute: () => AccountRouteRoute,
  } as any)
const AdminProductsIdIndexRoute = AdminProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFrontpageIdIndexRoute = AdminFrontpageIdIndexRouteImport.update({
  id: '/frontpage/$id/',
  path: '/frontpage/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIdIndexRoute = AdminCategoriesIdIndexRouteImport.update({
  id: '/categories/$id/',
  path: '/categories/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersIdIndexRoute = AccountOrdersIdIndexRouteImport.update({
  id: '/orders/$id/',
  path: '/orders/$id/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIdEditRoute = AdminCategoriesIdEditRouteImport.update({
  id: '/categories/$id/edit',
  path: '/categories/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountAddressBookIdEditRoute =
  AccountAddressBookIdEditRouteImport.update({
    id: '/address-book/$id/edit',
    path: '/address-book/$id/edit',
    getParentRoute: () => AccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/checkout/post-checkout': typeof CheckoutPostCheckoutRouteRouteWithChildren
  '/account/payments': typeof AccountPaymentsRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/add-category': typeof AdminAddCategoryRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$category': typeof CategoryIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/address-book/new-address': typeof AccountAddressBookNewAddressRoute
  '/admin/frontpage/new-frontpage': typeof AdminFrontpageNewFrontpageRoute
  '/$category/$product': typeof CategoryProductIndexRoute
  '/account/address-book': typeof AccountAddressBookIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/frontpage': typeof AdminFrontpageIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/checkout/post-checkout/': typeof CheckoutPostCheckoutIndexRoute
  '/products/$product': typeof ProductsProductIndexRoute
  '/account/address-book/$id/edit': typeof AccountAddressBookIdEditRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/account/orders/$id': typeof AccountOrdersIdIndexRoute
  '/admin/categories/$id': typeof AdminCategoriesIdIndexRoute
  '/admin/frontpage/$id': typeof AdminFrontpageIdIndexRoute
  '/admin/products/$id': typeof AdminProductsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/add-category': typeof AdminAddCategoryRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$category': typeof CategoryIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/address-book/new-address': typeof AccountAddressBookNewAddressRoute
  '/admin/frontpage/new-frontpage': typeof AdminFrontpageNewFrontpageRoute
  '/$category/$product': typeof CategoryProductIndexRoute
  '/account/address-book': typeof AccountAddressBookIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/frontpage': typeof AdminFrontpageIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/checkout/post-checkout': typeof CheckoutPostCheckoutIndexRoute
  '/products/$product': typeof ProductsProductIndexRoute
  '/account/address-book/$id/edit': typeof AccountAddressBookIdEditRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/account/orders/$id': typeof AccountOrdersIdIndexRoute
  '/admin/categories/$id': typeof AdminCategoriesIdIndexRoute
  '/admin/frontpage/$id': typeof AdminFrontpageIdIndexRoute
  '/admin/products/$id': typeof AdminProductsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/checkout/post-checkout': typeof CheckoutPostCheckoutRouteRouteWithChildren
  '/account/payments': typeof AccountPaymentsRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/add-category': typeof AdminAddCategoryRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$category/': typeof CategoryIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/address-book/new-address': typeof AccountAddressBookNewAddressRoute
  '/admin/frontpage/new-frontpage': typeof AdminFrontpageNewFrontpageRoute
  '/$category/$product/': typeof CategoryProductIndexRoute
  '/account/address-book/': typeof AccountAddressBookIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/frontpage/': typeof AdminFrontpageIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/checkout/post-checkout/': typeof CheckoutPostCheckoutIndexRoute
  '/products/$product/': typeof ProductsProductIndexRoute
  '/account/address-book/$id/edit': typeof AccountAddressBookIdEditRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/account/orders/$id/': typeof AccountOrdersIdIndexRoute
  '/admin/categories/$id/': typeof AdminCategoriesIdIndexRoute
  '/admin/frontpage/$id/': typeof AdminFrontpageIdIndexRoute
  '/admin/products/$id/': typeof AdminProductsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/search'
    | '/checkout/post-checkout'
    | '/account/payments'
    | '/account/security'
    | '/admin/add-category'
    | '/admin/add-product'
    | '/auth/login'
    | '/auth/register'
    | '/$category'
    | '/account/'
    | '/admin/'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/account/address-book/new-address'
    | '/admin/frontpage/new-frontpage'
    | '/$category/$product'
    | '/account/address-book'
    | '/account/orders'
    | '/admin/categories'
    | '/admin/frontpage'
    | '/admin/products'
    | '/checkout/post-checkout/'
    | '/products/$product'
    | '/account/address-book/$id/edit'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
    | '/account/orders/$id'
    | '/admin/categories/$id'
    | '/admin/frontpage/$id'
    | '/admin/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/search'
    | '/account/payments'
    | '/account/security'
    | '/admin/add-category'
    | '/admin/add-product'
    | '/auth/login'
    | '/auth/register'
    | '/$category'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/account/address-book/new-address'
    | '/admin/frontpage/new-frontpage'
    | '/$category/$product'
    | '/account/address-book'
    | '/account/orders'
    | '/admin/categories'
    | '/admin/frontpage'
    | '/admin/products'
    | '/checkout/post-checkout'
    | '/products/$product'
    | '/account/address-book/$id/edit'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
    | '/account/orders/$id'
    | '/admin/categories/$id'
    | '/admin/frontpage/$id'
    | '/admin/products/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/search'
    | '/checkout/post-checkout'
    | '/account/payments'
    | '/account/security'
    | '/admin/add-category'
    | '/admin/add-product'
    | '/auth/login'
    | '/auth/register'
    | '/$category/'
    | '/account/'
    | '/admin/'
    | '/cart/'
    | '/checkout/'
    | '/products/'
    | '/account/address-book/new-address'
    | '/admin/frontpage/new-frontpage'
    | '/$category/$product/'
    | '/account/address-book/'
    | '/account/orders/'
    | '/admin/categories/'
    | '/admin/frontpage/'
    | '/admin/products/'
    | '/checkout/post-checkout/'
    | '/products/$product/'
    | '/account/address-book/$id/edit'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
    | '/account/orders/$id/'
    | '/admin/categories/$id/'
    | '/admin/frontpage/$id/'
    | '/admin/products/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  SearchRoute: typeof SearchRoute
  CheckoutPostCheckoutRouteRoute: typeof CheckoutPostCheckoutRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  CategoryProductIndexRoute: typeof CategoryProductIndexRoute
  ProductsProductIndexRoute: typeof ProductsProductIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/$category/': {
      id: '/$category/'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/add-product': {
      id: '/admin/add-product'
      path: '/add-product'
      fullPath: '/admin/add-product'
      preLoaderRoute: typeof AdminAddProductRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/add-category': {
      id: '/admin/add-category'
      path: '/add-category'
      fullPath: '/admin/add-category'
      preLoaderRoute: typeof AdminAddCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/checkout/post-checkout': {
      id: '/checkout/post-checkout'
      path: '/checkout/post-checkout'
      fullPath: '/checkout/post-checkout'
      preLoaderRoute: typeof CheckoutPostCheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$product/': {
      id: '/products/$product/'
      path: '/products/$product'
      fullPath: '/products/$product'
      preLoaderRoute: typeof ProductsProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/post-checkout/': {
      id: '/checkout/post-checkout/'
      path: '/'
      fullPath: '/checkout/post-checkout/'
      preLoaderRoute: typeof CheckoutPostCheckoutIndexRouteImport
      parentRoute: typeof CheckoutPostCheckoutRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/frontpage/': {
      id: '/admin/frontpage/'
      path: '/frontpage'
      fullPath: '/admin/frontpage'
      preLoaderRoute: typeof AdminFrontpageIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/address-book/': {
      id: '/account/address-book/'
      path: '/address-book'
      fullPath: '/account/address-book'
      preLoaderRoute: typeof AccountAddressBookIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/$category/$product/': {
      id: '/$category/$product/'
      path: '/$category/$product'
      fullPath: '/$category/$product'
      preLoaderRoute: typeof CategoryProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/frontpage/new-frontpage': {
      id: '/admin/frontpage/new-frontpage'
      path: '/frontpage/new-frontpage'
      fullPath: '/admin/frontpage/new-frontpage'
      preLoaderRoute: typeof AdminFrontpageNewFrontpageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/address-book/new-address': {
      id: '/account/address-book/new-address'
      path: '/address-book/new-address'
      fullPath: '/account/address-book/new-address'
      preLoaderRoute: typeof AccountAddressBookNewAddressRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/products/$id/': {
      id: '/admin/products/$id/'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/frontpage/$id/': {
      id: '/admin/frontpage/$id/'
      path: '/frontpage/$id'
      fullPath: '/admin/frontpage/$id'
      preLoaderRoute: typeof AdminFrontpageIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/$id/': {
      id: '/admin/categories/$id/'
      path: '/categories/$id'
      fullPath: '/admin/categories/$id'
      preLoaderRoute: typeof AdminCategoriesIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/$id/': {
      id: '/account/orders/$id/'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/$id/edit': {
      id: '/admin/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof AdminCategoriesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/address-book/$id/edit': {
      id: '/account/address-book/$id/edit'
      path: '/address-book/$id/edit'
      fullPath: '/account/address-book/$id/edit'
      preLoaderRoute: typeof AccountAddressBookIdEditRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountAddressBookNewAddressRoute: typeof AccountAddressBookNewAddressRoute
  AccountAddressBookIndexRoute: typeof AccountAddressBookIndexRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
  AccountAddressBookIdEditRoute: typeof AccountAddressBookIdEditRoute
  AccountOrdersIdIndexRoute: typeof AccountOrdersIdIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountAddressBookNewAddressRoute: AccountAddressBookNewAddressRoute,
  AccountAddressBookIndexRoute: AccountAddressBookIndexRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
  AccountAddressBookIdEditRoute: AccountAddressBookIdEditRoute,
  AccountOrdersIdIndexRoute: AccountOrdersIdIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAddCategoryRoute: typeof AdminAddCategoryRoute
  AdminAddProductRoute: typeof AdminAddProductRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFrontpageNewFrontpageRoute: typeof AdminFrontpageNewFrontpageRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminFrontpageIndexRoute: typeof AdminFrontpageIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminCategoriesIdEditRoute: typeof AdminCategoriesIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
  AdminCategoriesIdIndexRoute: typeof AdminCategoriesIdIndexRoute
  AdminFrontpageIdIndexRoute: typeof AdminFrontpageIdIndexRoute
  AdminProductsIdIndexRoute: typeof AdminProductsIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAddCategoryRoute: AdminAddCategoryRoute,
  AdminAddProductRoute: AdminAddProductRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFrontpageNewFrontpageRoute: AdminFrontpageNewFrontpageRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminFrontpageIndexRoute: AdminFrontpageIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminCategoriesIdEditRoute: AdminCategoriesIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
  AdminCategoriesIdIndexRoute: AdminCategoriesIdIndexRoute,
  AdminFrontpageIdIndexRoute: AdminFrontpageIdIndexRoute,
  AdminProductsIdIndexRoute: AdminProductsIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CheckoutPostCheckoutRouteRouteChildren {
  CheckoutPostCheckoutIndexRoute: typeof CheckoutPostCheckoutIndexRoute
}

const CheckoutPostCheckoutRouteRouteChildren: CheckoutPostCheckoutRouteRouteChildren =
  {
    CheckoutPostCheckoutIndexRoute: CheckoutPostCheckoutIndexRoute,
  }

const CheckoutPostCheckoutRouteRouteWithChildren =
  CheckoutPostCheckoutRouteRoute._addFileChildren(
    CheckoutPostCheckoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  SearchRoute: SearchRoute,
  CheckoutPostCheckoutRouteRoute: CheckoutPostCheckoutRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  CategoryProductIndexRoute: CategoryProductIndexRoute,
  ProductsProductIndexRoute: ProductsProductIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
